### ISSUE TITLE
Review sequel-drill adapter

### ISSUE THREAD

**Issue by joeauty** [joeauty/sequel-drill#1]
Hey guys, I don't know if this is the best way to do this, but when you have a moment can you please review the working sequel-drill adapter?

https://github.com/thinkdata-works/sequel-drill/tree/develop

Once reviewed we can can operate off of PRs, but I figured this doesn't make sense without something to compare the changes against.

**Comment by ChrisSandison** [comment]
Left a comment on your PR re: organization

**Comment by joeauty** [comment]
Thanks @ChrisSandison !

**Comment by brendanstennett** [comment]
@joeauty Looks good to me! I think you identified a bunch of TODOs that you should create tickets for but other than that I think it's looking good.

Don't forget to publish the gem on RubyGems!

**Comment by joeauty** [comment]
Thanks Brendan! 

I will publish it once I've worked my way through more of the todos: https://github.com/joeauty/sequel-drill/issues

The big one in this list is support for table creation/importation, but I think I might just state in the README (which I will create shortly) that for now this is unsupported (and likewise for Hive stuff). In our platform it makes sense to me for this to happen outside of the adapter since the properties/schema comes from our API, so some work will be required to come up with an alternative.

I might just be creating a solution to a problem that doesn't exist though, it could be that other users of this adapter are content to import with a homemade SQL query generated outside of the adapter, so I'm thinking I'll just table this, publish it, and see what feedback (if any) we get.
