### ISSUE TITLE
add support for setting session variables 

### ISSUE THREAD

**Issue by drish** [joeauty/sequel-drill#30]
in order to run a query like this through the rest api:

```sql
alter session set `store.format`='csv';
create table dfs.`t` as select * from dfs.`x`
```

it is needed to create a session object with the http request.

more info:
http://mail-archives.apache.org/mod_mbox/drill-user/201605.mbox/%3CCAKOFcwrdwR2yTZK4a5dGLbOQ0P0yGWtOX6NrMSgRm6NSkk3myA@mail.gmail.com%3E

**Comment by joeauty** [comment]
I thought about sequel-drill supporting table creation, but figured that people will create tables in such a diverse range of ways and for us we wouldn't be using the Sequel adapter to help generate the syntax anyway. Table creation calls the execute function directly, can't we do the same thing to pass along the alter session query?

**Comment by drish** [comment]
hey @joeauty.

basically all queries that alters the session somehow (example: `use dfs.path;`, `alter session set`, etc), *would* require the query to be multiline like the example above and that fails with a syntax error.

So basically the way to go is to set session commands on the http request cookie.  

My proposal  is to have something similar to this.

```rb
client.session("alter session set `store.format`") do # stores this on the cookie session
  client.execute("select * from path") # actual query that goes into the json payload
end

or 

request = client.build_request
request.session = "alter session `store.format`='csv'" # goes into the cookie
request.execute("select * from ...")
```

**Comment by joeauty** [comment]
I see!

Happy to review PRs, I just invited you to be a repo collaborator...

**Comment by drish** [comment]
I actually misunderstood this issue a bit, I was under the assumption that it would be possible to send a cookie without being authenticated.

The library would basically need to support drill authentication, and after the user is logged in, it re-send the cookies generated by the login request.

So it would become:

```rb
client.auth(user, pass) do # logs in and server return cookies
  
  # each consecutive call inside the block sends the cookies
  client.execute("alter session `store.format`='csv' ")
  client.execute("select * from path")
end
```

**Comment by joeauty** [comment]
I guess there would also be a performance hit in having to do the alter session/set command before each query too? It would be great if these session options can be tied to users that Drill itself recognizes so that there can be some persistence of this setting.

**Comment by drish** [comment]
```rb
# stores session cookie on mem hash.
# can be done on application startup time.
client.authenticate!(user, pass)

client.authenticated? # true

client.execute("select * from dfs.`t`") # authenticated request.
```

if user tries to issue a not authenticated request.

```rb
# didn't authenticate before

# drill will return a non 200 res if authentication is enabled
# if not it will return response normally.
client.execute("select * from dfs.`t`")

# raises DrillAuthError
```
