### ISSUE TITLE
Reformat table names as parquet locations for all queries

### ISSUE THREAD

**Issue by mattpollack** [joeauty/sequel-drill#37]
Just moving the current regex into the execute method

**Comment by joeauty** [comment]
It would be far better if we got rid of the regex altogether. @drish and I have have some recommendations from the Sequel author as to what Sequel methods can be overridden to do this in a more elegant fashion than Regex.

**Comment by ChrisSandison** [comment]
@joeauty let's do that, but get the regex in in the meantime
